/**
 * Storage abstraction.
 *
 * Business logic depends ONLY on this interface, never on Backblaze specifics.
 * Swapping B2 for R2 or any S3-compatible service is a config change
 * (`STORAGE_PROVIDER`), not a code change.
 */

import { AppError } from '../utils/errors';

export interface PutObjectInput {
  key: string;
  body: ArrayBuffer | Uint8Array;
  contentType: string;
  /** Small metadata map persisted alongside the object where supported. */
  metadata?: Record<string, string>;
  /** Pre-computed sha-1 hex (B2) — computed automatically when omitted. */
  sha1?: string;
}

export interface PutObjectResult {
  key: string;
  size: number;
  etag?: string;
  versionId?: string;
}

export interface GetObjectResult {
  body: ReadableStream<Uint8Array>;
  size: number;
  contentType: string;
  etag?: string;
  lastModified?: number;
  metadata?: Record<string, string>;
}

export interface ObjectMetadata {
  key: string;
  size: number;
  contentType: string;
  etag?: string;
  lastModified?: number;
  metadata?: Record<string, string>;
}

export interface StorageProvider {
  readonly name: 'b2' | 's3' | 'r2';

  uploadObject(input: PutObjectInput): Promise<PutObjectResult>;

  /** `range` follows the HTTP Range syntax, e.g. "bytes=0-1023". */
  downloadObject(key: string, range?: string): Promise<GetObjectResult | null>;

  deleteObject(key: string): Promise<void>;

  headObject(key: string): Promise<ObjectMetadata | null>;

  objectExists(key: string): Promise<boolean>;

  getObjectMetadata(key: string): Promise<ObjectMetadata | null>;

  /**
   * Time-limited direct URL, when the backend supports it.
   * Returns null for providers where the Worker must proxy the bytes.
   */
  getSignedUrl?(key: string, expiresInSeconds: number): Promise<string | null>;
}

/**
 * Build a deterministic, collision-free object key.
 * Keys are derived server-side only — a client-supplied filename never
 * influences the path (that would allow traversal or overwrite attacks).
 */
export function generateObjectKey(params: {
  usage: 'avatar' | 'cover' | 'post' | 'attachment';
  ownerId: string;
  mediaId: string;
  extension: string;
  variant?: 'original' | 'thumb' | 'medium';
  postId?: string;
}): string {
  const { usage, ownerId, mediaId, postId } = params;
  const ext = sanitizeExtension(params.extension);
  const variant = params.variant ?? 'original';
  const suffix = variant === 'original' ? '' : `.${variant}`;
  const owner = sanitizeSegment(ownerId);
  const id = sanitizeSegment(mediaId);

  switch (usage) {
    case 'avatar':
      return `users/${owner}/avatar/${id}${suffix}.${ext}`;
    case 'cover':
      return `users/${owner}/cover/${id}${suffix}.${ext}`;
    case 'post':
      return postId
        ? `posts/${sanitizeSegment(postId)}/${id}${suffix}.${ext}`
        : `posts/_drafts/${owner}/${id}${suffix}.${ext}`;
    case 'attachment':
    default:
      return `attachments/${owner}/${id}${suffix}.${ext}`;
  }
}

/** Allow only characters that are safe in an object key path segment. */
export function sanitizeSegment(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9._-]/g, '').slice(0, 64);
  return cleaned || 'unknown';
}

export function sanitizeExtension(ext: string): string {
  const cleaned = ext.replace(/^\./, '').toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 8);
  return cleaned || 'bin';
}

/**
 * Guard against traversal or absolute keys reaching a storage backend.
 *
 * Keys are always generated by `generateObjectKey`, so reaching this throw
 * means an internal invariant broke — it is reported as a storage error, not
 * as a client mistake.
 */
export function assertSafeKey(key: string): void {
  if (
    !key ||
    key.length > 900 ||
    key.startsWith('/') ||
    key.includes('..') ||
    key.includes('//') ||
    /[\u0000-\u001f\u007f]/.test(key)
  ) {
    throw AppError.storage('Unsafe storage key');
  }
}
