/**
 * The notification dropdown.
 *
 * The panel itself is client-side, so what is tested here is the contract it
 * depends on: a cursor-paged endpoint that returns ten at a time with the text
 * and link already resolved, selective and bulk read marking, and the fact that
 * one member can never read or acknowledge another's notifications.
 */

import { describe, expect, it } from 'vitest';
import { TestClient } from './helpers/client';

interface NotificationItem {
  id: string;
  type: string;
  text: string;
  href: string;
  readAt: number | null;
}

interface NotificationPage {
  items: NotificationItem[];
  nextCursor: string | null;
  hasMore: boolean;
}

/**
 * One author with `count` follow notifications waiting.
 *
 * The first is generated by a real follow through the API, which is what proves
 * the wiring; the rest are inserted directly so the fixture is not throttled by
 * the (correct) five-registrations-an-hour limit and stays fast.
 */
async function withNotifications(count: number) {
  const author = new TestClient();
  const created = await author.register({ username: 'author', displayName: 'The Author' });

  const follower = new TestClient();
  Object.assign(follower, { env: author.env });
  await follower.register({ username: 'fan0', displayName: 'Fan 0' });
  await follower.post('/api/users/author/follow');

  const sqlite = author.env.db.sqlite;
  const actor = sqlite.prepare('SELECT id FROM users WHERE username = ?').get('fan0') as {
    id: string;
  };
  const insert = sqlite.prepare(
    `INSERT INTO notifications (id, user_id, actor_id, type, target_type, target_id, data_json, read_at, created_at)
     VALUES (?, ?, ?, 'FOLLOW', 'user', ?, '{}', NULL, ?)`,
  );
  const base = Math.floor(Date.now() / 1000);
  for (let i = 1; i < count; i++) {
    // A unique index collapses duplicate (recipient, actor, type, target)
    // notifications, so each row needs its own target id — and a distinct,
    // descending timestamp so cursor paging has a stable order.
    insert.run(
      `ntf_test${String(i).padStart(4, '0')}`,
      created.id,
      actor.id,
      `usr_target${String(i).padStart(4, '0')}`,
      base - i,
    );
  }

  return author;
}

describe('the notification feed behind the panel', () => {
  it('returns ten at a time with a cursor for the next ten', async () => {
    const author = await withNotifications(25);

    const first = await author.get<NotificationPage>('/api/notifications?limit=10');
    expect(first.status).toBe(200);
    expect(first.body.data!.items).toHaveLength(10);
    expect(first.body.data!.hasMore).toBe(true);

    const second = await author.get<NotificationPage>(
      `/api/notifications?limit=10&cursor=${encodeURIComponent(first.body.data!.nextCursor!)}`,
    );
    expect(second.body.data!.items).toHaveLength(10);

    // Two pages of ten fills the panel to its twenty-item cap with no overlap.
    const ids = new Set([
      ...first.body.data!.items.map((i) => i.id),
      ...second.body.data!.items.map((i) => i.id),
    ]);
    expect(ids.size).toBe(20);
  });

  it('resolves the summary text and the destination server-side', async () => {
    const author = await withNotifications(1);
    const page = await author.get<NotificationPage>('/api/notifications?limit=10');
    const item = page.body.data!.items[0]!;

    expect(item.type).toBe('FOLLOW');
    expect(item.text).toBe('Fan 0 started following you');
    expect(item.href).toBe('/u/fan0');
  });

  it('is never stored in a shared cache', async () => {
    const author = await withNotifications(1);
    const response = await author.get('/api/notifications');
    expect(response.headers.get('cache-control')).toContain('no-store');
  });

  it('requires a session', async () => {
    const anon = new TestClient();
    await anon.get('/login', { headers: { accept: 'text/html' } });
    expect((await anon.get('/api/notifications')).status).toBe(401);
  });
});

describe('marking notifications read', () => {
  it('marks a single notification without touching the others', async () => {
    const author = await withNotifications(3);
    const page = await author.get<NotificationPage>('/api/notifications?limit=10');
    const target = page.body.data!.items[0]!;

    const before = await author.get<{ count: number }>('/api/notifications/unread-count');
    expect(before.body.data!.count).toBe(3);

    const marked = await author.post<{ updated: number }>('/api/notifications/read', {
      ids: target.id,
    });
    expect(marked.body.data!.updated).toBe(1);

    const after = await author.get<{ count: number }>('/api/notifications/unread-count');
    expect(after.body.data!.count).toBe(2);

    const refreshed = await author.get<NotificationPage>('/api/notifications?limit=10');
    const row = refreshed.body.data!.items.find((i) => i.id === target.id)!;
    expect(row.readAt).not.toBeNull();
  });

  it('marks everything read in one call', async () => {
    const author = await withNotifications(4);
    const cleared = await author.post<{ updated: number }>('/api/notifications/read-all');
    expect(cleared.body.data!.updated).toBe(4);

    const count = await author.get<{ count: number }>('/api/notifications/unread-count');
    expect(count.body.data!.count).toBe(0);
  });

  it('cannot mark somebody else’s notification read', async () => {
    const author = await withNotifications(1);
    const page = await author.get<NotificationPage>('/api/notifications?limit=10');
    const target = page.body.data!.items[0]!;

    const stranger = new TestClient();
    Object.assign(stranger, { env: author.env });
    await stranger.register({ username: 'stranger' });

    // The query is scoped by user id, so this is a silent no-op rather than an
    // error — and crucially the owner's unread count is unchanged.
    const attempt = await stranger.post<{ updated: number }>('/api/notifications/read', {
      ids: target.id,
    });
    expect(attempt.body.data!.updated).toBe(0);

    const count = await author.get<{ count: number }>('/api/notifications/unread-count');
    expect(count.body.data!.count).toBe(1);
  });
});

describe('the panel markup', () => {
  it('ships the dropdown, its scroller and a "show all" link on every page', async () => {
    const author = await withNotifications(1);
    const page = await author.raw('/', { headers: { accept: 'text/html' } });
    const html = await page.text();

    expect(html).toContain('data-notif-panel');
    expect(html).toContain('data-notif-scroll');
    expect(html).toContain('data-notif-read-all');
    // "Show all" is a real link, so the panel degrades to the full page.
    expect(html).toContain('href="/notifications"');
  });

  it('does not render the panel for anonymous visitors', async () => {
    const anon = new TestClient();
    const page = await anon.raw('/', { headers: { accept: 'text/html' } });
    const html = await page.text();

    expect(html).not.toContain('data-notif-panel');
    expect(html).toContain('href="/login"');
  });

  it('gathers settings and the theme switch into the account menu', async () => {
    const author = await withNotifications(1);
    const page = await author.raw('/', { headers: { accept: 'text/html' } });
    const html = await page.text();

    expect(html).toContain('data-account-panel');
    expect(html).toContain('href="/settings"');
    expect(html).toContain('data-theme-toggle');
  });

  it('renders a phone navigation bar distinct from the desktop sidebar', async () => {
    const author = await withNotifications(1);
    const page = await author.raw('/', { headers: { accept: 'text/html' } });
    const html = await page.text();

    expect(html).toContain('class="mobilenav"');
    expect(html).toContain('mobilenav__link');
    // Reels is reachable from both navigations.
    expect(html).toContain('href="/reels"');
  });
});
